version: "3.9"

services:

  server:
    build: .
    deploy:
      replicas: 2
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  expired-location-job:
    build: ./expired-location-job/.
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
